import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ShopContextProvider from "./Context/ShopContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { BrowserRouter } from "react-router-dom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#050505] ${geistMono.variable} antialiased`}
      >
        <BrowserRouter>
          <ShopContextProvider>
            <Navbar/>
            <div className="px-12">
            {children}
            </div>
            <Footer/>
            
          </ShopContextProvider>
          </BrowserRouter>
      </body>
    </html>
  );
}
